name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
        working-directory: ./app
      - name: Lint
        run: npm run lint
        working-directory: ./app
      - name: Test
        run: npm test -- --ci
        working-directory: ./app
      - name: Export web
        run: npx expo export -p web --output-dir dist
        working-directory: ./app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: app/dist