apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
  labels:
    app: ai-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
    spec:
      containers:
        - name: ai-engine
          image: novax/ai-engine:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai
                  key: apiKey
          readinessProbe:
            httpGet:
              path: /api/ai/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/ai/health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine
spec:
  selector:
    app: ai-engine
  ports:
    - name: http
      port: 80
      targetPort: 3001