apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: novax/payment:latest
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: secret
            - name: PAYPAL_MODE
              value: sandbox
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: paypal
                  key: clientId
            - name: PAYPAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: paypal
                  key: clientSecret
          readinessProbe:
            httpGet:
              path: /api/payment/health
              port: 3003
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/payment/health
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - name: http
      port: 80
      targetPort: 3003