name: EAS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Print Expo Doctor
        working-directory: apps/mobile
        run: npx expo doctor || true

      - name: Trigger EAS build (production)
        working-directory: apps/mobile
        run: |
          eas build --platform all --profile production --non-interactive --no-wait | tee build.log

      - name: Upload EAS build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eas-build-log
          path: apps/mobile/build.log

      - name: Post EAS build URLs
        if: always()
        working-directory: apps/mobile
        run: |
          echo "See builds at: https://expo.dev/accounts/_/projects/ello-replica/builds"